### ISSUE TITLE
The latest update is not working properly

### ISSUE THREAD

**Issue by anhdodotnet** [alexlaverty/ttsvibelounge#10]
1 - The latest update is not working properly, it hangs in place as shown and doesn't work

![image](https://user-images.githubusercontent.com/25850343/197204917-360fe555-131b-41ce-982b-2dc667078856.png)

2 - settings.py 
 ```
# choices "polly","balcon","gtts"
voice_engine = "gtts" 
```
When you configure the "choices to gTTS" part will be error:
![image](https://user-images.githubusercontent.com/25850343/197205785-d8c25b34-d1a8-43b1-a35c-cd2c0e893793.png)

**Comment by alexlaverty** [comment]
Can you send me the reddit post url it was trying to process I'll see if I can reproduce and troubleshoot the error. Maybe was a blank line or something

**Comment by alexlaverty** [comment]
I've pushed a commit to skip trying to generate a clip for a blank line :
https://github.com/alexlaverty/ttsvibelounge/commit/5284e895f3006a5c7e7ff264025cb3121ee5fc34

**Comment by anhdodotnet** [comment]
> Can you send me the reddit post url it was trying to process I'll see if I can reproduce and troubleshoot the error. I can see in the screenshot `comment line :` appears blank

it's been stopping at this process for 30 minutes:
![image](https://user-images.githubusercontent.com/25850343/197310088-aa1d0a04-b499-4bcc-9dda-8d28f30adbef.png)
![image](https://user-images.githubusercontent.com/25850343/197310163-20a72efd-0a30-450d-9d08-9eae8c8a225a.png)

**Comment by anhdodotnet** [comment]
**--story-mode      Generate video for post title and selftext only, disables user comments:**
_(Video processing has also stopped here and has not seen activity for more than 20 minutes ... and possibly more.)_
![image](https://user-images.githubusercontent.com/25850343/197310839-081bebdd-060d-47b1-b3ee-f709ad58ee09.png)

**Comment by anhdodotnet** [comment]
i configured the video length to be 327s why does it take 600s when running

![image](https://user-images.githubusercontent.com/25850343/197324395-1a326ced-9882-4012-9891-a6d04b94cba8.png)
