### ISSUE TITLE
New update ... version 2? ... SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by anhdodotnet** [alexlaverty/ttsvibelounge#19]
![image](https://user-images.githubusercontent.com/25850343/198614074-51901766-a65e-48f2-9dc8-84e6d4e69b34.png)

**Comment by alexlaverty** [comment]
I don't seem to have `print prompt` anywhere in my codebase, do you have another pip package installed that might be colliding with it? do you have this library installed with the same name ?  https://pypi.org/project/speech/

**Comment by anhdodotnet** [comment]
> I don't seem to have `print prompt` anywhere in my codebase, do you have another pip package installed that might be colliding with it? do you have this library installed with the same name ? https://pypi.org/project/speech/

I tried deleting PIP and reinstalling it, but I still get this error... in the old version I still work fine

**Comment by anhdodotnet** [comment]
I also tried installing it on my laptop... it still doesn't work

**Comment by anhdodotnet** [comment]
I have removed python3 and reinstalled... I think there are some conflicts.

**Comment by alexlaverty** [comment]
Did you manage to resolve it? You can also run this code via docker which will replicate how I'm running it, need to have docker installed https://www.docker.com/ and then should just be able to do :
```
docker-compose up 
```
takes quite a while to build the image for the first time though.
