### ISSUE TITLE
I have a few questions need your help?

### ISSUE THREAD

**Issue by anhdodotnet** [alexlaverty/ttsvibelounge#22]
1. In the process of processing when there is an error in an article, can tools skip that article and continue to process the next article?
**p/s:** while using the tools i noticed when it encounters an error it will automatically exit the process of processing the following articles... i need it to work and continue to get the error in the above post.

2. Error:  **Timeout 30000ms exceeded.** Is this error fixable? I often get this error 30%
3. Video title (final.mp4) can replace article title instead of "final"
4. Remove the excess of thumb
![image](https://user-images.githubusercontent.com/25850343/198908710-0ecdaab9-a843-4f6b-8c92-dba7dabd65fd.png)

5. Is it possible to select a folder image (rondom IMAGE thumb)?

**Comment by anhdodotnet** [comment]
I'm getting this error

![image](https://user-images.githubusercontent.com/25850343/199364222-1e3c0d69-7f48-4cf0-a21e-c5e0cdb367fc.png)

**Comment by alexlaverty** [comment]
I've pushed some updates to the thumbnail.py so it generates thumbnails like so, was pretty tricky to get that colouring per line thing working... 
![thumbnail_0](https://user-images.githubusercontent.com/4024404/199467072-917d4925-4ec8-4fc0-b8e5-78aa41e76eee.png)

I've pushed some changes to allow configurable timeout values for the comment screenshotting so try playing around with increasing this value in `settings.py` and see if it helps with the timeout errors that you're getting :

```
comment_screenshot_timeout = 30000
```

will be pushing the code up soon
