### ISSUE TITLE
Move files screenhort and audio to TEMP FOLDER?

### ISSUE THREAD

**Issue by anhdodotnet** [alexlaverty/ttsvibelounge#23]
Screenhort and audio files can be grouped into a temporary folder by article id

It works like the tool (elebumm/RedditVideoMakerBot)
![image](https://user-images.githubusercontent.com/25850343/199131700-8000b2f0-aa73-49d1-a454-7aaecd4ede58.png)

**Comment by alexlaverty** [comment]
Will look into it when I have some time
