### ISSUE TITLE
How to create an automatic thumb image for video?

### ISSUE THREAD

**Issue by anhdodotnet** [alexlaverty/ttsvibelounge#3]
I can create a thumbnail image without creating a video? (I want to create a thumb image for another video
)

**Comment by alexlaverty** [comment]
I have added thumbnail only mode, pull latest master and try :

```
python app.py --thumbnail-only
```

**Comment by anhdodotnet** [comment]
> I have added thumbnail only mode, pull latest master and try :
> 
> ```
> python app.py --thumbnail-only
> ```

I want to create any thumbnail image by taking a content content reddit id, like the command?

python app.py --thumbnail-only --url https://www.reddit.com/r/AskMen/comments/y0j6il/men_in_romantic_relationships_what_would_you_do/

**Comment by anhdodotnet** [comment]
> I have added thumbnail only mode, pull latest master and try :
> 
> ```
> python app.py --thumbnail-only
> ```

Very cool, I tested it for 1 container ID, it works fine, thank you.
