### ISSUE TITLE
"Missing either client_secrets.json or credentials file" error 

### ISSUE THREAD

**Issue by anhdodotnet** [alexlaverty/ttsvibelounge#41]
I've been trying to upload videos to the channel, where did I go wrong?
![image](https://user-images.githubusercontent.com/25850343/200119046-a7817e45-7c40-4db0-b8e4-24f45196cb9d.png)

![image](https://user-images.githubusercontent.com/25850343/200119093-1661fde3-029a-41c3-9306-260bbae87533.png)
![image](https://user-images.githubusercontent.com/25850343/200119099-9a71bb4a-513f-40cc-8773-2932fb98d616.png)

**Comment by alexlaverty** [comment]
When you ran upload for the first time did you complete the outh2 web login? once completed that should create the credentials storage file :

![image](https://user-images.githubusercontent.com/4024404/200287142-1a6723da-aec7-404b-886a-13fdb669dc96.png)

See if you can run `python test_upload.py` on its own to complete the oauth verification and generate the file

**Comment by anhdodotnet** [comment]
OH, that's awesome... i'm trying it... Thank you so much

**Comment by anhdodotnet** [comment]
Schedule video publishing, have you deployed ít? I'm really looking forward to this feature :)

**Comment by anhdodotnet** [comment]
I'm wondering, can you add a little function...create video using reddit search keyword?
![image](https://user-images.githubusercontent.com/25850343/200441777-b4b12f93-0bb5-456e-8882-87106d025dde.png)

**Comment by alexlaverty** [comment]
> Schedule video publishing, have you deployed ít? I'm really looking forward to this feature :)

I am running the script on a schedule via Github Action workflow, see the config for it :
https://github.com/alexlaverty/ttsvibelounge/issues/41

**Comment by anhdodotnet** [comment]
Thank you, I will test it

**Comment by anhdodotnet** [comment]
> > Schedule video publishing, have you deployed ít? I'm really looking forward to this feature :)
> 
> I am running the script on a schedule via Github Action workflow, see the config for it : https://github.com/alexlaverty/ttsvibelounge/blob/main/.github/workflows/tssvibelounge.yml
> 
> Apart from adding that file into your github repo, you also need to go into `Settings --> Secrets --> Actions` and add entries for your settings accordingly :
> 
> ![image](https://user-images.githubusercontent.com/4024404/200522177-8d65ee8f-4a69-4a60-8e23-184179a04489.png)
