### ISSUE TITLE
Error random auto create video make?

### ISSUE THREAD

**Issue by anhdodotnet** [alexlaverty/ttsvibelounge#5]
Hello @alexlaverty 

1. I noticed when I execute the command copy custom url ID content ( python app.py --url 1,2,3,4,5,6,7 ....) the tool works fine.
2. However when I do select some groups in the (settings.py) section it throws an error:
![image](https://user-images.githubusercontent.com/25850343/196566219-dd8b23c7-5fc0-4729-932a-8cd4794c2003.png)
In this image I have selected several groups: 
`subreddits = [
    "AskMen",
    "relationship_advice",
    "relationships",
    "TrueOffMyChest",
    "cheating_stories",
    "JUSTNOMIL",
    "AskWomen",
    "TwoXChromosomes"
    ]`
you see in the subreddits there is no (AskReddit) but when executing the command run aap.py tool it retrieves the post in AskReddit. 
As a result it gives an error:
![image](https://user-images.githubusercontent.com/25850343/196566892-72f8d62f-9e8d-471a-8899-92a78db11cca.png)

**Comment by alexlaverty** [comment]
Fixed the subreddits bug, issue was code was hardcoded to "all" subreddit, can see the fix in this commit :
https://github.com/alexlaverty/ttsvibelounge/commit/5c1cb4808b1180473b80bbf4d9a1a91dadeb243a

and fixed the second bug as well i think, possibly that post didn't have an author, maybe user account had been deleted or something? Added a check to see if comment.author exists before attempting to echo it :
https://github.com/alexlaverty/ttsvibelounge/commit/fc328306ce18b12a8991394cd7e8bcdda844dc8e

Let me know how you go!

**Comment by anhdodotnet** [comment]
> Fixed the subreddits bug, issue was code was hardcoded to "all" subreddit, can see the fix in this commit : [5c1cb48](https://github.com/alexlaverty/ttsvibelounge/commit/5c1cb4808b1180473b80bbf4d9a1a91dadeb243a)
> 
> and fixed the second bug as well i think, possibly that comment didn't have an author, maybe user account had been deleted or something? Added a check to see if comment.author exists before attempting to echo it : [fc32830](https://github.com/alexlaverty/ttsvibelounge/commit/fc328306ce18b12a8991394cd7e8bcdda844dc8e)
> 
> Let me know how you go!

I updated and it works great. Thank you so much.
