### ISSUE TITLE
implementation of story mode

### ISSUE THREAD

**Issue by beezisback** [alexlaverty/ttsvibelounge#8]
Can you implement story mode?
To read only the topic without reading the comments, it would be an excellent function for some subreddits such as those with stories

**Comment by alexlaverty** [comment]
I have pushed an update which will allow story mode :
https://github.com/alexlaverty/ttsvibelounge/commit/1eff497a7e9833d635db2a92c0f1951e77105c44

You can now run story mode via :
```
python app.py --story-mode
```

This will read the post title and selftext and skip the user comments, thanks for the suggestion let me know how you go!
