### ISSUE TITLE
EdgeTTS and streamlabs_polly as an alternative to gTTS 

### ISSUE THREAD

**Issue by beezisback** [alexlaverty/ttsvibelounge#9]
Can you please add edgeTTS and streamlabs_polly as an alternative to gTTS because there are times when it speaks very slowly.
I am attaching examples in which they have been implemented.
I await your feedback
thanks
[TTS.zip](https://github.com/alexlaverty/ttsvibelounge/files/9838978/TTS.zip)

**Comment by beezisback** [comment]
also TikTokTTS it's a good ideea. the problem is that it must be limited to 300 characters for each request. I tried to implement it myself but I didn't succeed. I have a lot to learn
[tt1.zip](https://github.com/alexlaverty/ttsvibelounge/files/9841478/tt1.zip)

**Comment by alexlaverty** [comment]
I'll look into it, yeh I will need to figure out how to do chunks of 300 characters at a time and put it back together

**Comment by becauseimnoob** [comment]
I'm waiting for edgeTTS feature too 👍

**Comment by beezisback** [comment]
> I'll look into it, yeh I will need to figure out how to do chunks of 300 characters at a time and put it back together

[tt.zip](https://github.com/alexlaverty/ttsvibelounge/files/9844974/tt.zip)
you can adapt this one it's already splitting the text but you also need the session id to generate the tts

**Comment by alexlaverty** [comment]
@beezisback I have borrowed some of that code for supporting tiktok, thanks for that!

**Comment by alexlaverty** [comment]
I'm looking into edge-tts now should be done soon

**Comment by alexlaverty** [comment]
have implemented edge-tts and streamlabs polly, closing issue
